Repository github/stale-repos, pull requests merged in 2023-06, with the labels that each got.

#29 Add inactive repos as action output
  README.md
  action.yml
  stale_repos.py
Labels: enhancement

#30 Json testing
  .coveragerc
  Makefile
  stale_repos.py
  test_stale_repos.py
Labels: infrastructure

#36 Enable personal accounts when no org is present
  .gitignore
  README.md
  stale_repos.py
Labels: enhancement

#37 Write JSON data to file
  README.md
  stale_repos.py
  test_stale_repos.py
Labels: enhancement

#38 feat: Add exemption labels for repositories
  README.md
  stale_repos.py
  test_stale_repos.py
Labels: enhancement

#40 Add multiple org example to README
  README.md
Labels: documentation

#41 docs: fix token permissions in README
  README.md
Labels: documentation

#45 use only major rev for less frequent README changes
  README.md
Labels: documentation

#46 Update base image version to python 3.11
  Dockerfile
Labels: infrastructure

#47 infra: add docker to dependabot
  .github/dependabot.yml
  .gitignore
Labels: infrastructure

#49 feat: Add last push date to markdown and JSON output files
  README.md
  stale_repos.py
  test_stale_repos.py
Labels: enhancement
