Repository github/stale-repos, pull requests merged in 2024-05, with the labels that each got.

#130 chore: add OSSF scorecard github action and README badge
  .github/workflows/scorecard.yml
  README.md
Labels: maintenance

#131 chore: security remediation after turning on ossf scorecoard
  .github/workflows/auto-labeler.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/docker-image.yml
  .github/workflows/linter.yaml
  .github/workflows/pr-title.yml
  .github/workflows/python-package.yml
  .github/workflows/release.yml
  .github/workflows/use-action.yml
  Dockerfile
Labels: maintenance

#136 chore: change last few github actions to use shas
  .github/workflows/integration_tests.disabled
  .github/workflows/major-version-updater.yml
  .github/workflows/release.yml
  .github/workflows/stale.yaml
  .github/workflows/use-action.yml
Labels: maintenance

#138 chore: group dependabot dependency updates for minor/patch updates
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/docker-image.yml
  .github/workflows/linter.yaml
  .github/workflows/major-version-updater.yml
  .github/workflows/pr-title.yml
  .github/workflows/python-package.yml
  .github/workflows/release.yml
  .github/workflows/scorecard.yml
Labels: maintenance, release

#140 chore: delete unneeded custom codeql GitHub Action
  .github/workflows/codeql-analysis.yml
Labels: maintenance

#143 chore: Switch to weekly dep updates to reduce noise
  .github/dependabot.yml
Labels: maintenance

#147 chore: add pull_request_target for releases
  .github/workflows/release.yml
  .github/workflows/use-action.yml
Labels: maintenance

#150 ci: release when a new feature hits main
  .github/workflows/release.yml
Labels: automation

#151 chore: remove pull_request target if we already have pull_request_target
  .github/workflows/auto-labeler.yml
  .github/workflows/release.yml
  README.md
Labels: maintenance

#153 ci: Add Jeff to review new data releases
  .github/pull_request_template.md
Labels: automation
