Repository github/stale-repos, pull requests merged in 2024-06, with the labels that each got.

#156 chore: add Jacob to pr reviews automatically
  .github/CODEOWNERS
Labels: maintenance

#157 chore: standardize github action types
  .github/workflows/auto-labeler.yml
  .github/workflows/docker-image.yml
  .github/workflows/linter.yaml
  .github/workflows/major-version-updater.yml
  .github/workflows/pr-title.yml
  .github/workflows/python-package.yml
  .github/workflows/release.yml
  .github/workflows/scorecard.yml
  .github/workflows/use-action.yml
Labels: maintenance

#158 feat: additional metrics for days since last release and PR
  .env-example
  README.md
  stale_repos.py
  test_stale_repos.py
Labels: feature

#164 ci: hard coded dates to declarative
  test_stale_repos.py
Labels: automation
