Repository github/stale-repos, pull requests merged in 2024-03, with the labels that each got.

#87 feat: add repository visibility (public/private) to output
  README.md
  stale_repos.py
  test_stale_repos.py
Labels: enhancement

#92 feat: allow user to use github app to authenticate
  .env-example
  Makefile
  README.md
  stale_repos.py
  test_stale_repos.py
Labels: enhancement

#94 strip out spaces for people like me that dont follow the directions
  stale_repos.py
Labels: bug

#96 fix: linting
  .github/workflows/codeql-analysis.yml
  .github/workflows/docker-image.yml
  .github/workflows/linter.yaml
  .github/workflows/major-version-updater.yml
  .github/workflows/python-package.yml
  .github/workflows/release-drafter.yml
  .github/workflows/use-action.yml
  README.md
Labels: enhancement

#97 Create stale.yaml
  .github/workflows/stale.yaml
Labels: infrastructure

#100 Use Keep label to exempt from stale action
  .github/workflows/stale.yaml
Labels: infrastructure

#99 fix: permissions in Dockerfile when trying to output
  Dockerfile
Labels: bug

#102 chore: add black linter to `make lint`
  Makefile
  requirements-test.txt
Labels: infrastructure

#103 fix: go back to root user in Dockefile
  Dockerfile
Labels: bug

#105 chore: linting config setup
  .github/linters/.flake8
  Makefile
Labels: infrastructure
