Repository github/stale-repos, pull requests merged in 2024-04, with the labels that each got.

#108 chore: catch up repo standards
  .github/linters/.isort.cfg
  .github/linters/.mypy.ini
  .github/linters/isort.cfg
  Makefile
  README.md
  requirements-test.txt
Labels: documentation

#113 docs: add github issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  README.md
Labels: documentation

#117 enhancement: Check if archived before checking labels and dates for performance
  stale_repos.py
Labels: enhancement

#118 feat: automated releases and auto labelling
  .github/ISSUE_TEMPLATE/config.yml
  .github/pull_request_template.md
  .github/workflows/auto-labeler.yml
  .github/workflows/pr-title.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  CONTRIBUTING.md
Labels: enhancement

#120 fix: add autolabeler config
  .github/release-drafter.yml
Labels: maintenance

#124 chore(deps): update dependabot config to include pr prefixes
  .github/dependabot.yml
  .github/pull_request_template.md
  requirements-test.txt
Labels: maintenance

#128 feat: release on specific labels
  .github/release-drafter.yml
  .github/workflows/release.yml
  CONTRIBUTING.md
  requirements-test.txt
Labels: enhancement
