Repository github/stale-repos, pull requests merged in 2024-02, with the labels that each got.

#79 Support determining activity date from default branch
  README.md
  stale_repos.py
  test_stale_repos.py
Labels: enhancement

#80 Update issuecreation action to v5
  README.md
Labels: documentation

#83 return None in case of a github exception for get_active_date
  stale_repos.py
  test_stale_repos.py
Labels: bug

#84 Update README.md to include reference to github-ospo
  README.md
Labels: documentation

#88 chore: local testing without Docker
  README.md
  requirements-test.txt
Labels: documentation, infrastructure
