Repository github/stale-repos, pull requests merged in 2025-01, with the labels that each got.

#244 feat: move to reusable workflows
  .github/release-drafter.yml
  .github/workflows/auto-labeler.yml
  .github/workflows/major-version-updater.yml
  .github/workflows/pr-title.yml
  .github/workflows/release.yml
Labels: feature

#246 fix: use correct image name for releases
  .github/workflows/release.yml
Labels: fix, release

#248 fix: image name has underscore, not dash like repo
  .github/workflows/release.yml
Labels: fix, release

#250 fix: use explicit image name for release
  .github/workflows/release.yml
Labels: fix, release

#252 fix: need owner included with image name
  .github/workflows/release.yml
Labels: fix, release

#254 feat: drop support for python 3.9
  .github/workflows/python-package.yml
  README.md
Labels: release, feature, breaking

#225 feat: support github enterprise api
  .env-example
  .github/linters/.isort.cfg
  .github/linters/.python-lint
  README.md
  auth.py
  stale_repos.py
  test_auth.py
  test_stale_repos.py
Labels: feature

#259 fix: use GH_TOKEN env var for token
  stale_repos.py
Labels: fix, release

#268 chore: update semver
  .github/release-drafter.yml
Labels: maintenance
